---
- name: Download Lazyvim config
  hosts: server1
  become: true
  gather_facts: true
  tasks:
    - name: Install nvim package using dnf
      git:
        clone: true
        repo: 'https://github.com/LazyVim/starter'
        dest: /home/erik/.config/nvim

- name: Install Fuzy Find "fzf" on server1
  hosts: server1
  become: true
  gather_facts: true
  tasks:
    - name: Install fzf package using dnf
      dnf:
        name: fzf
        state: present
        install_weak_deps: yes
    
    - name: Verify fzf installation
      command: fzf --version
      register: fzf_version
      changed_when: false
    
    - name: Display fzf version
      debug:
        msg: "fzf version installed: {{ fzf_version.stdout }}"

- name: Install ripgrep on server1
  hosts: server1
  become: true
  gather_facts: true
  tasks:
    - name: Install ripgrep package using dnf
      dnf:
        name: ripgrep
        state: present
        install_weak_deps: yes
    
    - name: Verify ripgrep installation
      command: rg --version
      register: ripgrep_version
      changed_when: false
    
    - name: Display ripgrep version
      debug:
        msg: "ripgrep version installed: {{ ripgrep_version.stdout }}"

- name: Install fd-find on server1
  hosts: server1
  become: true
  gather_facts: true
  tasks:
    - name: Install fd-find package using dnf
      dnf:
        name: fd-find
        state: present
        install_weak_deps: yes
    
    - name: Verify fd-find installation
      command: fd --version
      register: fdfind_version
      changed_when: false
    
    - name: Display fd-find version
      debug:
        msg: "fdfind version installed: {{ fdfind_version.stdout }}"

- name: Add COPR repository and install lazygit
  hosts: server1
  become: true
  gather_facts: true
  tasks:
    - name: Ensure dnf-plugins-core is installed
      dnf:
        name: dnf-plugins-core
        state: present
    
    - name: Add COPR repository using dnf copr command
      command: dnf copr enable {{ copr_user }}/{{ copr_project }} -y
      args:
        creates: "/etc/yum.repos.d/_copr:copr.fedorainfracloud.org:{{ copr_user }}:{{ copr_project }}.repo"
      vars:
        copr_user: "atim"
        copr_project: "lazygit"
    
    - name: Verify repository was added
      command: dnf repolist --enabled
      register: repo_list
      changed_when: false
    
    - name: Show enabled repositories
      debug:
        msg: "{{ repo_list.stdout_lines }}"
    
    - name: Install package from COPR repository
      dnf:
        name: lazygit
        state: present
      when: "'copr:copr.fedorainfracloud.org:atim:lazygit' in repo_list.stdout"

    - name: Verify lazygit installation
      command: lazygit --version
      register: lazygit_version
      changed_when: false
    
    - name: Display lazygit version
      debug:
        msg: "lazygit version installed: {{ lazygit_version.stdout }}"
